#!/usr/bin/python
#This is the main program. It should be *very* simple.
import slit_server
import sys
sys.path.append('..')
import server_socket
slits=slit_server.SlitServer()
ss=server_socket.ServerSocket(23451, 'slit', slits)	
ss.add_job(slits.slit_client)
ss.run()
ss.close()
