#!/usr/bin/env python
#This is the main program. It should be *very* simple.
import subprocess,sys,os

#the following lines establish a link with the starlight xpress camera via the USB port, these run 
#automatically when sx_main is excecuted
try: 
        if not os.path.exists('/tmp/sx_fifo'):
                dummy=subprocess.call('mkfifo /tmp/sx_fifo', shell=True)
        if not ('indiserver' and '/tmp/sx_fifo') in os.popen("ps aux").read():
                indiserver_process=subprocess.Popen(['indiserver','-f','/tmp/sx_fifo','-p','7777'],stdin=subprocess.PIPE, stdout=subprocess.PIPE)
                #indiserver_process=subprocess.Popen('indiserver -f /tmp/sx_fifo -p 7777',shell=True)
                sxserver_process=subprocess.Popen(['echo','start indi_sx_ccd','>','/tmp/sx_fifo'],stdin=subprocess.PIPE, stdout=subprocess.PIPE)
                #procs=[indiserver_process]
except Exception: print 'Unable to start indi server'

def kill_everything(ss,server,processes):
        server.indi.quit()
        ss.close()
        for i in processes:
                i.terminate()
                returncode = i.wait()
        print 'Successfully terminated the indiserver with return code: %s' % returncode
        sys.exit()

import subaru_server
sys.path.append('../common')
import server_socket
import find_port
f = find_port.FindPort()
Port = f.findPort('sx')
sx=subaru_server.Subaru()
ss=server_socket.ServerSocket(Port, 'subaru', sx)	
ss.add_job(sx.checkIfFinished)
#ss.add_job(sx.heaterControl)
#ss.add_job(sx.feedbackLoop)
try: ss.run()
except KeyboardInterrupt:
        kill_everything(ss,subaru_server,[sxserver_process,indiserver_process])
kill_everything(ss,subaru_server,[sxserver_process,indiserver_process])
