#!/usr/bin/python
#This is the main program. It should be *very* simple.
import labjack_server
import sys
import os
sys.path.append('..')
import server_socket
import find_port
f = find_port.FindPort()
Port = f.findPort('labjack')
lj=labjack_server.LabjackServer()
ss=server_socket.ServerSocket(Port, 'labjack', lj)	
ss.add_job(lj.dome_location)
ss.add_job(lj.home_tracker)
ss.run()
ss.close()
