#!/usr/bin/python
#This is the main program. It should be *very* simple.
import meademount_server
import sys
sys.path.append('..')
import server_socket
mm=meademount_server.MeademountServer()
ss=server_socket.ServerSocket(23457, 'meademount', mm)	
ss.add_job(mm.too_low_check)
ss.run()
ss.close()
