#!/usr/bin/python
#This is the main program. It should be *very* simple.
import meademount_server
import sys
sys.path.append('..')
import server_socket
mm=meademount_server.MeademountServer()
ss=server_socket.ServerSocket(23458, 'meademount', mm)	
ss.run()
ss.close()
