#!/usr/bin/env python
#This is the main program. It should be *very* simple.
import weatherstation_server
import sys
sys.path.append('../common')
import server_socket
import find_port
f = find_port.FindPort()
Port = f.findPort('weatherstation')
ws=weatherstation_server.WeatherstationServer()
ss=server_socket.ServerSocket(Port, 'weatherstation', ws)	
ss.add_job(ws.serialread)
ss.run()
ss.close()
