#!/usr/bin/python
#This is the main program. It should be *very* simple.
import weatherstation_server
import sys
sys.path.append('..')
import server_socket
ws=weatherstation_server.WeatherstationServer()
ss=server_socket.ServerSocket(23450, 'weatherstation', ws)	
ss.add_job(ws.serialread)
ss.run()
ss.close()
