#!/usr/bin/python
#This is the main program. It should be *very* simple.
import imagingsourcecamera_server
import sys
sys.path.append('../common/')
import server_socket
import find_port
f = find_port.FindPort()
Port = f.findPort('')
isc=imagingsourcecamera_server.ImagingSourceCameraServer()
ss=server_socket.ServerSocket(Port, 'imagingsourcecamera', isc)	
ss.run()
ss.close()
