#!/usr/bin/env python
#This is the main program. It should be *very* simple.
import scheduler_server
import sys
sys.path.append('../common')
import server_socket
import find_port
f = find_port.FindPort()
Port = f.findPort('scheduler')
sch=scheduler_server.SchedServer()
ss=server_socket.ServerSocket(Port, 'scheduler', sch)
#ss.add_job(sch.imaging_loop)
ss.run()
ss.close()
