#!/usr/bin/python
#This is the main program. It should be *very* simple.
import imagingsourcecamera_server
import sys
sys.path.append('..')
import server_socket
isc=imagingsourcecamera_server.ImagingSourceCameraServer()
ss=server_socket.ServerSocket(23459, 'imagingsourcecamera', isc)	
ss.run()
ss.close()
