#!/usr/bin/env python
#This is the main program. It should be *very* simple.
import uber_server
import sys
sys.path.append('../common/')
import server_socket
import find_port
f = find_port.FindPort()
Port = f.findPort('uber')
ub=uber_server.UberServer()
ss=server_socket.ServerSocket(Port, 'uber', ub)
ss.add_job(ub.monitor_slits)
ss.add_job(ub.dome_track)
ss.add_job(ub.guiding_loop)
ss.add_job(ub.imaging_loop)
ss.add_job(ub.server_check)
ss.run()
ss.close()
