#!/usr/bin/python
#This is the main program. It should be *very* simple.
import uber_server
import sys
#sys.path.append('../common')
import server_socket
ub=uber_server.UberServer()
ss=server_socket.ServerSocket(23555, 'Super User', ub)
ss.add_job(ub.monitor_slits)
ss.add_job(ub.dome_track)
ss.add_job(ub.guiding_loop)
ss.add_job(ub.imaging_loop)
ss.run()
ss.close()
