#!/usr/bin/python
#This is the main program. It should be *very* simple.
import sbigudrv_server
import sys
sys.path.append('..')
import server_socket
import find_port
f = find_port.FindPort()
#Port = f.findPort('sbig')
sb=sbigudrv_server.SBigUDrv()
ss=server_socket.ServerSocket(23460, 'sbigudrv', sb)	
ss.run()
ss.close()
