#!/usr/bin/python
#This is the main program. It should be *very* simple.
import sbigudrv_server
import sys
sys.path.append('../common')
import server_socket
import find_port
f = find_port.FindPort()
#Port = f.findPort('sbig')
sb=sbigudrv_server.SBigUDrv()
ss=server_socket.ServerSocket(23460, 'sbigudrv', sb)	
ss.add_job(sb.imaging_loop)
ss.add_job(sb.checkIfFinished)
ss.run()
ss.close()
