#!/usr/bin/python
#This is the main program. It should be *very* simple.
import bisquemount_server
import sys
sys.path.append('../common')
import server_socket
import find_port
f = find_port.FindPort()
Port = f.findPort('telescope')
bm=bisquemount_server.BisqueMountServer()
ss=server_socket.ServerSocket(Port, 'bisquemount', bm)	
ss.add_job(bm.adjustFocus)
ss.run()
ss.close()
